"""partners

Revision ID: 3f43c37bfd2d
Revises: f25e0484f824
Create Date: 2018-12-10 13:28:47.209242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f43c37bfd2d'
down_revision = 'f25e0484f824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partnerships',
    sa.Column('partner_a_id', sa.Integer(), nullable=True),
    sa.Column('partner_b_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['partner_a_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['partner_b_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partnerships')
    # ### end Alembic commands ###
