"""empty message

Revision ID: 6e1afc2c56d6
Revises: ccfccd2c21d4
Create Date: 2018-12-12 13:19:06.555792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e1afc2c56d6'
down_revision = 'ccfccd2c21d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitation', sa.Column('receiver_username', sa.String(length=64), nullable=True))
    op.add_column('invitation', sa.Column('sender_username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_invitation_receiver_id'), 'invitation', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_invitation_sender_id'), 'invitation', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invitation_sender_id'), table_name='invitation')
    op.drop_index(op.f('ix_invitation_receiver_id'), table_name='invitation')
    op.drop_column('invitation', 'sender_username')
    op.drop_column('invitation', 'receiver_username')
    # ### end Alembic commands ###
